### ISSUE TITLE
case_matrix.yaml

### ISSUE THREAD

**Issue by tatesnow** [NREL/pCrunch#14]
Can you share the case_matrix.yaml file you used in the batch_processing.ipynb file?

**Comment by gbarter** [comment]
@ptrbortolotti @nikhar-abbas Did one of you put that example together?

**Comment by nikhar-abbas** [comment]
Hi @tatesnow,
I put this example together but unfortunately don't have the case_matrix.yaml file. The case matrix file is generated using the aeroelasticse module of the [WEIS](https://github.com/wisdem/weis) toolset, or using the casegen functions in [ROSCO](https://github.com/NREL/ROSCO/tree/main/ROSCO_toolbox/ofTools). You can find examples of how these tools are used to generate and run OpenFAST simulations [here](https://github.com/WISDEM/WEIS/blob/master/examples/01_aeroelasticse/run_general.py) in WEIS, and as a part of the [testing](https://github.com/NREL/ROSCO/tree/main/ROSCO_testing) in ROSCO. Functionally, the same code is used in both WEIS and ROSCO. 

Just FYI, we will soon be merging the develop branch of pCrunch into main, so it might make your workflow easier in the future if you set up your current tools according to the develop branch. You can find an example Jupyter notebook [here](https://github.com/NREL/pCrunch/blob/develop/example.ipynb) that is not dependent on the case_matrix.yaml file. Similarly, the example python script [here](https://github.com/NREL/pCrunch/blob/develop/postProcessing/post_BatchRun.py) can be used for guidance.

In both the master and develop branches of pCrunch, the case_matrix.yaml file is not necessary for the main functions, thoough it does help with easing the workflow in some circumstances (e.g., when using the get_windspeeds function). 

Hopefully this helps,
Nikhar
