### ISSUE TITLE
Error loading case matrix into dataframe

### ISSUE THREAD

**Issue by mlidGWT** [NREL/pCrunch#27]
Hello, I'm sure this is simple for someone better versed in Python; I tried running `post_BatchRun.py` on some of my results and I'm getting an error message that is difficult for me to troubleshoot: 

> AttributeError: 
"load()" has been removed, use
  yaml = YAML(typ='rt')
  yaml.load(...)
and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "/var/folders/_5/d3c371ds5s51tt6k66y9fnh40000gn/T/ipykernel_7706/1351518608.py", line 76
        case_matrix = ry.load(f, Loader=ry.Loader)

I tried replacing that line (#76) with the suggested lines, 
`yaml = YAML(typ='rt')`
`case_matrix = yaml.load(f)` 
but then get an error that 'YAML' is undefined. Is this placeholder text for something else, like the 'yaml.load(...)' in the error message? Is there another package I need to import? 

Thanks in advance for the help!

**Comment by gbarter** [comment]
I updated that [file](https://github.com/NREL/pCrunch/blob/master/examples/post_BatchRun.py) a few weeks ago to solve some problems that have cropped up in the upstream python yaml libraries.  Please sync with the latest version and let me know if the problem persists.

**Comment by mlidGWT** [comment]
Hi Garrett, 
I just tried again with the linked file and I'm getting the same error. I only installed pCrunch today using `conda install pCrunch` - not sure if there are any additional steps needed. 

> Traceback (most recent call last):
  File "/Users/meglidrbauch/[path]/post_BatchRun.py", line 76, in <module>
    case_matrix = ry.load(f, Loader=ry.Loader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/meglidrbauch/miniconda3/envs/weisfresh-env/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1085, in load
    error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  File "/Users/meglidrbauch/miniconda3/envs/weisfresh-env/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"load()" has been removed, use
  yaml = YAML(typ='rt')
  yaml.load(...)
and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "/Users/meglidrbauch/[path]/post_BatchRun.py", line 76
        case_matrix = ry.load(f, Loader=ry.Loader)

**Comment by gbarter** [comment]
I removed the deprecated function call [here](https://github.com/NREL/pCrunch/commit/eb57ac5c7c71e68eebf39de4b39fd3c981050b7c), in the `develop` branch.  Is that sufficient for you or would it be easiest to push this through all the way to a version increment and new conda package?

**Comment by mlidGWT** [comment]
Hello, apologies I thought I had responded to this last week. That file worked for me, thank you for the help!
